{{ config(
    materialized = 'table',
    schema = 'MARTS'
) }}

SELECT
    STATE_FIPS,
    STATE_NAME,
    YEAR,

    RETAIL_ESTABLISHMENTS,
    RETAIL_EMPLOYMENT,
    RETAIL_ANNUAL_PAYROLL,

    TOTAL_GDP_ANNUAL,
    RETAIL_GDP_ANNUAL,
    RETAIL_GDP_SHARE,

    RETAIL_EMPLOYMENT
        / NULLIF(RETAIL_ESTABLISHMENTS, 0)
        AS RETAIL_EMPLOYMENT_PER_ESTABLISHMENT,

    RETAIL_ANNUAL_PAYROLL
        / NULLIF(RETAIL_EMPLOYMENT, 0)
        AS RETAIL_PAYROLL_PER_EMPLOYEE,

    RETAIL_GDP_ANNUAL
        / NULLIF(RETAIL_ESTABLISHMENTS, 0)
        AS RETAIL_GDP_PER_ESTABLISHMENT,

    RETAIL_GDP_ANNUAL
        / NULLIF(RETAIL_EMPLOYMENT, 0)
        AS RETAIL_GDP_PER_RETAIL_EMPLOYEE

FROM {{ ref('int_retail_market') }}